import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../core/services/database_service.dart';
import '../../core/theme/app_colors.dart';
import '../../core/theme/app_text_styles.dart';
import '../../core/theme/app_spacing.dart';
import 'models/product_model.dart';
import '../profile/models/purchase_model.dart';

class ProductDetailScreen extends StatefulWidget {
  final String? productId;
  const ProductDetailScreen({super.key, this.productId});

  @override
  State<ProductDetailScreen> createState() => _ProductDetailScreenState();
}

class _ProductDetailScreenState extends State<ProductDetailScreen> {
  final DatabaseService _db = DatabaseService();
  ProductModel? _product;
  bool _isLoading = true;
  int _quantity = 1;

  @override
  void initState() {
    super.initState();
    _loadProduct();
  }

  Future<void> _loadProduct() async {
    try {
      final products = await _db.getAllProducts();
      final product = products.firstWhere((p) => p.id == widget.productId);
      setState(() {
        _product = product;
        _isLoading = false;
      });
    } catch (e) {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _handleBuyNow() async {
    if (_product == null) return;

    setState(() => _isLoading = true);
    try {
      final purchase = PurchaseModel(
        id: '', // Will be generated by Firestore
        uid: 'user_123',
        productName: _product!.name,
        productCategory: _product!.category,
        price: _product!.price * _quantity,
        quantity: _quantity,
        purchaseDate: DateTime.now(),
        status: 'Completed',
        imageUrl: _product!.imageUrl,
      );

      await _db.purchaseProduct('user_123', purchase);
      
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Purchase successful! Item added to your history.'),
            backgroundColor: AppColors.success,
          ),
        );
        context.pop(); // Go back to marketplace
      }
    } catch (e) {
      if (mounted) {
         ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e'), backgroundColor: AppColors.error),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return const Scaffold(body: Center(child: CircularProgressIndicator()));
    }

    if (_product == null) {
      return Scaffold(
        appBar: AppBar(backgroundColor: AppColors.primaryGreen),
        body: const Center(child: Text('Product not found')),
      );
    }

    return Scaffold(
      backgroundColor: Colors.transparent,
      appBar: AppBar(
        title: Text('Product Details', style: AppTextStyles.appBarTitle),
        backgroundColor: AppColors.primaryGreen,
        iconTheme: const IconThemeData(color: Colors.white),
        elevation: 0,
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Product Image
            Container(
              height: 300,
              width: double.infinity,
              color: Colors.grey[100],
              child: _product!.imageUrl.isNotEmpty
                ? Image.network(_product!.imageUrl, fit: BoxFit.cover)
                : const Icon(Icons.shopping_basket, size: 100, color: Colors.grey),
            ),
            
            Padding(
              padding: const EdgeInsets.all(AppSpacing.md),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Category & Organic Tag
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                        decoration: BoxDecoration(
                          color: AppColors.primaryContainer,
                          borderRadius: BorderRadius.circular(20),
                        ),
                        child: Text(
                          _product!.category,
                          style: AppTextStyles.labelSmall.copyWith(color: AppColors.primaryGreen),
                        ),
                      ),
                      if (_product!.isOrganic)
                        const Row(
                          children: [
                            Icon(Icons.eco, color: AppColors.primaryGreen, size: 16),
                            SizedBox(width: 4),
                            Text('Organic Certified', style: TextStyle(color: AppColors.primaryGreen, fontWeight: FontWeight.bold, fontSize:12)),
                          ],
                        ),
                    ],
                  ),
                  
                  const SizedBox(height: AppSpacing.md),
                  
                  // Product Name
                  Text(
                    _product!.name,
                    style: AppTextStyles.displayMedium.copyWith(fontSize: 24, color: AppColors.textPrimary),
                  ),
                  
                  const SizedBox(height: AppSpacing.sm),
                  
                  // Price
                  Text(
                    '₹${_product!.price.toStringAsFixed(0)}',
                    style: AppTextStyles.headingLarge.copyWith(color: AppColors.primaryGreen, fontSize: 32),
                  ),

                  const SizedBox(height: AppSpacing.lg),

                  // Description
                  Text('Description', style: AppTextStyles.headingSmall),
                  const SizedBox(height: AppSpacing.sm),
                  Text(
                    _product!.description,
                    style: AppTextStyles.bodyMedium.copyWith(color: AppColors.textSecondary, height: 1.5),
                  ),

                  const SizedBox(height: 100), // Space for bottom button
                ],
              ),
            ),
          ],
        ),
      ),
      bottomNavigationBar: Container(
        padding: const EdgeInsets.all(AppSpacing.md),
        decoration: BoxDecoration(
          color: AppColors.white,
          boxShadow: [
            BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 10, offset: const Offset(0, -4)),
          ],
        ),
        child: SafeArea(
          child: Row(
            children: [
              // Quantity Picker
              Container(
                decoration: BoxDecoration(
                  border: Border.all(color: Colors.grey[300]!),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Row(
                  children: [
                    IconButton(
                      icon: const Icon(Icons.remove),
                      onPressed: () {
                        if (_quantity > 1) setState(() => _quantity--);
                      },
                    ),
                    Text('$_quantity', style: AppTextStyles.bodyMedium.copyWith(fontWeight: FontWeight.bold)),
                    IconButton(
                      icon: const Icon(Icons.add),
                      onPressed: () => setState(() => _quantity++),
                    ),
                  ],
                ),
              ),
              const SizedBox(width: AppSpacing.md),
              // Buy Now Button
              Expanded(
                child: SizedBox(
                  height: 54,
                  child: ElevatedButton(
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.primaryGreen,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                      elevation: 0,
                    ),
                    onPressed: _isLoading ? null : _handleBuyNow,
                    child: _isLoading 
                      ? const CircularProgressIndicator(color: Colors.white)
                      : Text('Buy Now', style: AppTextStyles.displayMedium.copyWith(color: AppColors.white, fontSize: 18)),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
