// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX9jpPFHICfaNVATREu1ZzXDXvTRGTj4U',
    appId: '1:305117925606:web:bf3edf17d74964e8592b27',
    messagingSenderId: '305117925606',
    projectId: 'cropapp-7c33e',
    authDomain: 'cropapp-7c33e.firebaseapp.com',
    storageBucket: 'cropapp-7c33e.firebasestorage.app',
    measurementId: 'G-XCB6Z9QVQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCwBGLIMZy20E77qmlc93MsdHr61jouz8',
    appId: '1:305117925606:android:f1fa22f97d883e86592b27',
    messagingSenderId: '305117925606',
    projectId: 'cropapp-7c33e',
    storageBucket: 'cropapp-7c33e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1OpVAiuPwhOtE6JM9QUvvnMeQkkUW2Jk',
    appId: '1:305117925606:ios:ffe678d143c6b972592b27',
    messagingSenderId: '305117925606',
    projectId: 'cropapp-7c33e',
    storageBucket: 'cropapp-7c33e.firebasestorage.app',
    iosBundleId: 'com.cropsecure.cropsecureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1OpVAiuPwhOtE6JM9QUvvnMeQkkUW2Jk',
    appId: '1:305117925606:ios:ffe678d143c6b972592b27',
    messagingSenderId: '305117925606',
    projectId: 'cropapp-7c33e',
    storageBucket: 'cropapp-7c33e.firebasestorage.app',
    iosBundleId: 'com.cropsecure.cropsecureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX9jpPFHICfaNVATREu1ZzXDXvTRGTj4U',
    appId: '1:305117925606:web:041e7f152dc3ba7d592b27',
    messagingSenderId: '305117925606',
    projectId: 'cropapp-7c33e',
    authDomain: 'cropapp-7c33e.firebaseapp.com',
    storageBucket: 'cropapp-7c33e.firebasestorage.app',
    measurementId: 'G-YTLKWR6TX5',
  );
}
